aws_access_key = "xxxxxx"
aws_secret_key = "xxxxxx"
aws_region = "us-east-1"
vpc_cidr = "10.1.0.0/16"
public_subnet1_cidr = "10.1.1.0/24"
vpc_name = "Prod_VPC"
IGW_name = "Prod_IGW"
public_subnet1_name = "Prod_Subnet"
Main_Routing_Table = "Prod_Route"
key_name = "veera_dont_delete.key"
environment = "Prod"

