aws_access_key = "AKIAQWW3NNRLUYEIOJL3"
aws_secret_key = "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"
aws_region = "us-east-1"
vpc_cidr = "10.1.0.0/16"
public_subnet1_cidr = "10.1.1.0/24"
vpc_name = "terraform-aws-testing"
IGW_name = "terraform-aws-igw"
public_subnet1_name = "Terraform_Public_Subnet1-testing"
Main_Routing_Table = "Terraform_Main_table-testing"
key_name = "veera_dont_delete.key"
environment = "dev"

