aws_access_key = "xxxxxx"
aws_secret_key = "xxxxxx"
aws_region = "us-east-1"
vpc_cidr = "10.61.0.0/16"
public_subnet1_cidr = "10.61.1.0/24"
vpc_name = "Test_VPC"
IGW_name = "Test_IGW"
public_subnet1_name = "Test_Subnet"
Main_Routing_Table = "Test_Route"
key_name = "veera_dont_delete.key"
environment = "Test"

