aws_access_key = "xxxxx"
aws_secret_key = "xxxxx"
aws_region = "us-east-1"
vpc_cidr = "10.41.0.0/16"
public_subnet1_cidr = "10.41.1.0/24"
vpc_name = "Dev_VPC"
IGW_name = "Dev_IGW"
public_subnet1_name = "Dev_Subnet"
Main_Routing_Table = "Dev_Route"
key_name = "veera_dont_delete.key"
environment = "Dev"

